print(10 > 9)
print(10 == 9)
print(10 < 9)
print(134 > 39)
print(10 == 923)
print(12340 < 3945)

print(bool("abc"))
print(bool(123))
print(bool(["apple", "cherry", "banana"]))
print(bool("az"))
print(bool(1))
print(bool(["almaty", "aktay", "atrau"]))

print(bool(False))
print(bool(None))
print(bool(0))
print(bool(""))
print(bool(()))
print(bool([]))
print(bool({}))